// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4smDGpnAjxXprAJJNMsm4F
// Component: KHUctKZ4wl3yj
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_lti_organizer_version_2.module.css"; // plasmic-import: 4smDGpnAjxXprAJJNMsm4F/projectcss
import * as sty from "./PlasmicLearnMoreCard.module.css"; // plasmic-import: KHUctKZ4wl3yj/css

export type PlasmicLearnMoreCard__VariantMembers = {};

export type PlasmicLearnMoreCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicLearnMoreCard__VariantsArgs;
export const PlasmicLearnMoreCard__VariantProps = new Array<VariantPropType>();

export type PlasmicLearnMoreCard__ArgsType = {};
type ArgPropType = keyof PlasmicLearnMoreCard__ArgsType;
export const PlasmicLearnMoreCard__ArgProps = new Array<ArgPropType>();

export type PlasmicLearnMoreCard__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultLearnMoreCardProps {
  className?: string;
}

function PlasmicLearnMoreCard__RenderFunc(props: {
  variants: PlasmicLearnMoreCard__VariantsArgs;
  args: PlasmicLearnMoreCard__ArgsType;
  overrides: PlasmicLearnMoreCard__OverridesType;
  dataFetches?: PlasmicLearnMoreCard__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box__gcrxJ)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__vA7A
          )}
        >
          <span>
            <span style={{ fontWeight: 700 }}>{"Tool"}</span>
            <React.Fragment>{"\nZoom\n"}</React.Fragment>
          </span>
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__knvvt
          )}
        >
          <span>
            <span style={{ fontWeight: 700 }}>{"Description"}</span>
            <React.Fragment>
              {"\nProvides access to the Zoom video conference platform.\n"}
            </React.Fragment>
          </span>
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box___5Et19
          )}
        >
          <span>
            <span style={{ fontWeight: 700 }}>{"Privacy Agreement"}</span>
            <React.Fragment>{"\nData Protection Addendum\n"}</React.Fragment>
          </span>
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__jh8XM
          )}
        >
          <span>
            <span style={{ fontWeight: 700 }}>{"Placements in Canvas"}</span>
            <React.Fragment>{"\nCourse Navigation\n"}</React.Fragment>
          </span>
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__lur
          )}
        >
          <span>
            <span style={{ fontWeight: 700 }}>{"Support Resources"}</span>
            <React.Fragment>
              {"\nITS Teaching with Zoom Guide (would be link)"}
            </React.Fragment>
          </span>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLearnMoreCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLearnMoreCard__VariantsArgs;
    args?: PlasmicLearnMoreCard__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicLearnMoreCard__Fetches;
  } & Omit<PlasmicLearnMoreCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLearnMoreCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLearnMoreCard__ArgProps,
      internalVariantPropNames: PlasmicLearnMoreCard__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicLearnMoreCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLearnMoreCard";
  } else {
    func.displayName = `PlasmicLearnMoreCard.${nodeName}`;
  }
  return func;
}

export const PlasmicLearnMoreCard = Object.assign(
  // Top-level PlasmicLearnMoreCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicLearnMoreCard
    internalVariantProps: PlasmicLearnMoreCard__VariantProps,
    internalArgProps: PlasmicLearnMoreCard__ArgProps
  }
);

export default PlasmicLearnMoreCard;
/* prettier-ignore-end */
