// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4smDGpnAjxXprAJJNMsm4F
// Component: I2Tl4s0MjH4lI
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Ratings from "../../Ratings"; // plasmic-import: 9LQQvRQk5Agsp/component
import LinkButton from "../../LinkButton"; // plasmic-import: _dAnqW-cFBjXk/component
import AddRemoveButton from "../../AddRemoveButton"; // plasmic-import: Jken9iMDI9nE3/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_lti_organizer_version_2.module.css"; // plasmic-import: 4smDGpnAjxXprAJJNMsm4F/projectcss
import * as sty from "./PlasmicProductCard.module.css"; // plasmic-import: I2Tl4s0MjH4lI/css

import ShoppingCartIcon from "./icons/PlasmicIcon__ShoppingCart"; // plasmic-import: mb2PBuZZT34ygW/icon
import HeartOIcon from "./icons/PlasmicIcon__HeartO"; // plasmic-import: 8xEF_dULebj1bL/icon
import ExpandIcon from "./icons/PlasmicIcon__Expand"; // plasmic-import: BYOf1_7pBlohEy/icon
import panoptoLogo2GBrjx0UjVniCmu from "./images/panoptoLogo2.png"; // plasmic-import: gBrjx0ujVNICmu/picture
import panoptoNWNvdBMzLrZH from "./images/panopto.png"; // plasmic-import: nWNvdB-MZLrZ-h/picture

export type PlasmicProductCard__VariantMembers = {
  withReviews: "withReviews";
};

export type PlasmicProductCard__VariantsArgs = {
  withReviews?: SingleBooleanChoiceArg<"withReviews">;
};

type VariantPropType = keyof PlasmicProductCard__VariantsArgs;
export const PlasmicProductCard__VariantProps = new Array<VariantPropType>(
  "withReviews"
);

export type PlasmicProductCard__ArgsType = {
  title?: React.ReactNode;
  image?: React.ReactNode;
  ratings?: React.ReactNode;
  logo?: React.ReactNode;
  description?: React.ReactNode;
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicProductCard__ArgsType;
export const PlasmicProductCard__ArgProps = new Array<ArgPropType>(
  "title",
  "image",
  "ratings",
  "logo",
  "description",
  "children"
);

export type PlasmicProductCard__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultProductCardProps {
  title?: React.ReactNode;
  image?: React.ReactNode;
  ratings?: React.ReactNode;
  logo?: React.ReactNode;
  description?: React.ReactNode;
  children?: React.ReactNode;
  withReviews?: SingleBooleanChoiceArg<"withReviews">;
  className?: string;
}

function PlasmicProductCard__RenderFunc(props: {
  variants: PlasmicProductCard__VariantsArgs;
  args: PlasmicProductCard__ArgsType;
  overrides: PlasmicProductCard__OverridesType;
  dataFetches?: PlasmicProductCard__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const [isRootHover, triggerRootHoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_root: isRootHover
  };

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__withReviews]: hasVariant(
          variants,
          "withReviews",
          "withReviews"
        )
      })}
      data-plasmic-trigger-props={[triggerRootHoverProps]}
    >
      <div
        className={classNames(defaultcss.all, sty.box__jDzq1, {
          [sty.box__withReviews__jDzq1VKFlC]: hasVariant(
            variants,
            "withReviews",
            "withReviews"
          )
        })}
      >
        <div className={classNames(defaultcss.all, sty.box__u5Xyp)}>
          {p.renderPlasmicSlot({
            defaultContents: (
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___0H8Dx)}
                role={"img"}
                src={panoptoLogo2GBrjx0UjVniCmu}
              />
            ),

            value: args.logo
          })}
        </div>
      </div>

      {p.renderPlasmicSlot({
        defaultContents: "Panopto is used to record, share and manage videos.",
        value: args.description
      })}

      <div
        className={classNames(defaultcss.all, sty.box__iPrPp, {
          [sty.box__withReviews__iPrPpvKFlC]: hasVariant(
            variants,
            "withReviews",
            "withReviews"
          )
        })}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__w7Y8A)}
              role={"img"}
              src={panoptoNWNvdBMzLrZH}
            />
          ),

          value: args.image
        })}

        {false ? (
          <div className={classNames(defaultcss.all, sty.box__px3Ok)}>
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__ngRx
              )}
            >
              {"Sale"}
            </div>
          </div>
        ) : null}
        {(triggers.hover_root ? false : false) ? (
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__fagCy)}
          >
            <ShoppingCartIcon
              className={classNames(defaultcss.all, sty.svg__q3Q8)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__to2TX
              )}
            >
              {"Add to cart"}
            </div>

            <HeartOIcon
              className={classNames(defaultcss.all, sty.svg__kfCMs)}
              role={"img"}
            />

            <ExpandIcon
              className={classNames(defaultcss.all, sty.svg__y57S2)}
              role={"img"}
            />
          </p.Stack>
        ) : null}
      </div>

      {(hasVariant(variants, "withReviews", "withReviews") ? true : false)
        ? p.renderPlasmicSlot({
            defaultContents: (
              <Ratings
                className={classNames("__wab_instance", sty.ratings___5N28R)}
              />
            ),

            value: args.ratings
          })
        : null}

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box___9SnDc)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Title",
          value: args.title,
          className: classNames(sty.slotTitle)
        })}
      </p.Stack>

      <div className={classNames(defaultcss.all, sty.box___5Mn3Z)}>
        <LinkButton
          className={classNames("__wab_instance", sty.linkButton___48Kzf)}
          text={p.renderPlasmicSlot({
            defaultContents: (
              <AddRemoveButton
                className={classNames(
                  "__wab_instance",
                  sty.addRemoveButton__hqtbc
                )}
                removeToolFromSite={"removeToolFromSite" as const}
              />
            ),

            value: args.children
          })}
        />

        <LinkButton
          className={classNames("__wab_instance", sty.linkButton__tImt0)}
          text={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__xIiXi
              )}
            >
              {"Learn More"}
            </div>
          }
        />
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProductCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProductCard__VariantsArgs;
    args?: PlasmicProductCard__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicProductCard__Fetches;
  } & Omit<PlasmicProductCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicProductCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicProductCard__ArgProps,
      internalVariantPropNames: PlasmicProductCard__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicProductCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProductCard";
  } else {
    func.displayName = `PlasmicProductCard.${nodeName}`;
  }
  return func;
}

export const PlasmicProductCard = Object.assign(
  // Top-level PlasmicProductCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicProductCard
    internalVariantProps: PlasmicProductCard__VariantProps,
    internalArgProps: PlasmicProductCard__ArgProps
  }
);

export default PlasmicProductCard;
/* prettier-ignore-end */
