// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4smDGpnAjxXprAJJNMsm4F
// Component: 9LQQvRQk5Agsp
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_lti_organizer_version_2.module.css"; // plasmic-import: 4smDGpnAjxXprAJJNMsm4F/projectcss
import * as sty from "./PlasmicRatings.module.css"; // plasmic-import: 9LQQvRQk5Agsp/css

import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: b-ZwK9Bxn2B4rd/icon

export type PlasmicRatings__VariantMembers = {
  stars: "zero" | "one" | "two" | "three" | "four" | "five";
};

export type PlasmicRatings__VariantsArgs = {
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
};

type VariantPropType = keyof PlasmicRatings__VariantsArgs;
export const PlasmicRatings__VariantProps = new Array<VariantPropType>("stars");

export type PlasmicRatings__ArgsType = {
  numReviews?: React.ReactNode;
};

type ArgPropType = keyof PlasmicRatings__ArgsType;
export const PlasmicRatings__ArgProps = new Array<ArgPropType>("numReviews");

export type PlasmicRatings__OverridesType = {
  root?: p.Flex<"div">;
  box?: p.Flex<"div">;
};

export interface DefaultRatingsProps {
  numReviews?: React.ReactNode;
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
  className?: string;
}

function PlasmicRatings__RenderFunc(props: {
  variants: PlasmicRatings__VariantsArgs;
  args: PlasmicRatings__ArgsType;
  overrides: PlasmicRatings__OverridesType;
  dataFetches?: PlasmicRatings__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__stars_five]: hasVariant(variants, "stars", "five"),
        [sty.root__stars_four]: hasVariant(variants, "stars", "four"),
        [sty.root__stars_one]: hasVariant(variants, "stars", "one"),
        [sty.root__stars_three]: hasVariant(variants, "stars", "three"),
        [sty.root__stars_two]: hasVariant(variants, "stars", "two"),
        [sty.root__stars_zero]: hasVariant(variants, "stars", "zero")
      })}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box)}
      >
        {(hasVariant(variants, "stars", "zero") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__prSys, {
              [sty.svg__stars_five__prSysm6Hk4]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_zero__prSysF7Pif]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__bUpSx, {
              [sty.svg__stars_five__bUpSxm6Hk4]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__bUpSxrfWXr]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__bUpSxpOej]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__bUpSxzGPoB]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__bUpSxuv6Z5]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__bUpSxF7Pif]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__zUSxt, {
              [sty.svg__stars_five__zUSxtm6Hk4]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__zUSxtrfWXr]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__zUSxtpOej]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__zUSxtzGPoB]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__zUSxtuv6Z5]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__zUSxtF7Pif]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__esZil, {
              [sty.svg__stars_five__esZiLm6Hk4]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__esZiLrfWXr]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__esZiLpOej]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__esZiLzGPoB]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__esZiLuv6Z5]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__esZilf7Pif]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__afDo, {
              [sty.svg__stars_five__afDom6Hk4]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__afDorfWXr]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__afDopOej]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__afDozGPoB]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__afDouv6Z5]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__afDoF7Pif]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? true
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__ppDfJ, {
              [sty.svg__stars_five__ppDfJm6Hk4]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__ppDfJrfWXr]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__ppDfJpOej]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__ppDfJzGPoB]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__ppDfJuv6Z5]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__ppDfJf7Pif]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__hU5Pz, {
              [sty.svg__stars_five__hU5PZm6Hk4]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__hU5PZrfWXr]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_three__hU5PZzGPoB]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__hU5PZuv6Z5]: hasVariant(
                variants,
                "stars",
                "two"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__rMj4D, {
              [sty.svg__stars_five__rMj4Dm6Hk4]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__rMj4DrfWXr]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_three__rMj4DzGPoB]: hasVariant(
                variants,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__cLouZ, {
              [sty.svg__stars_five__cLouZm6Hk4]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__cLouZrfWXr]: hasVariant(
                variants,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__gtTsn, {
              [sty.svg__stars_five__gtTsnm6Hk4]: hasVariant(
                variants,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotNumReviews)
      })}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  box: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRatings__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRatings__VariantsArgs;
    args?: PlasmicRatings__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicRatings__Fetches;
  } & Omit<PlasmicRatings__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRatings__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),

    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
